//******************************************************************//
//*           Automatically Generated File Please Do Edit          *//
//******************************************************************//

//Description   : An Implementation for Instruction ldc_w  (0x13) (019)        
//Generated by  : Eslam Al-Morshdy (eslam@gmx.de)                        
//for Bugs      :                                         				  
//Last Edited by:												      



//========
//CAUTIONS :
//========
//	 (1) - Nothig Goes Here or it will be Lost in later Modification !
//	 (2) - Namming Convention  for local variables of an instruction 
//	        implementation should have a prefix that refrence the instruction 



//=========
//VARIABLES :
//=========
//	 unsigned int   	  pc     ;    /* program counter   */	
//	 unsigned int*  	  op_stk ;    /* operand stack     */	
//	 unsigned int*  	  locals ;    /* local variables   */	
//	 e_byte_t*            code  ;    /*byte-code stream   */	


#define e_CORE_ldc_w 	 \
	 e_CORE_ldc_w_START:   \
	{\
	 	auto e_j_u_integer word;\
		constant_pool->getWord(e_READ_FROM__JAVA_BYTE_STREAM_16((code_sofar+1),e_j_char),word);\
		e_PUSH_OPERAND_STACK((e_j_u_integer) word);\
	}\
	 e_CORE_ldc_w_END: 

