//******************************************************************//
//*           Automatically Generated File Please Do Edit          *//
//******************************************************************//

//Description   : An Implementation for Instruction getstatic  (0xb2) (178)        
//Generated by  : Eslam Al-Morshdy (eslam@gmx.de)                        
//for Bugs      :                                         				  
//Last Edited by:												      



//========
//CAUTIONS :
//========
//	 (1) - Nothig Goes Here or it will be Lost in later Modification !
//	 (2) - Namming Convention  for local variables of an instruction 
//	        implementation should have a prefix that refrence the instruction 



//=========
//VARIABLES :
//=========
//	 unsigned int   	  pc     ;    /* program counter   */	
//	 unsigned int*  	  op_stk ;    /* operand stack     */	
//	 unsigned int*  	  locals ;    /* local variables   */	
//	 e_byte_t*            code  ;    /*byte-code stream   */	


#define e_CORE_getstatic 	 \
	 e_CORE_getstatic_START:   \
	{\
		auto u4 word1,word2;\
		Field * field = constant_pool->getFieldData(e_READ_FROM__JAVA_BYTE_STREAM_16((code_sofar+1),e_j_char ));\
		char * p = field->getDesc();\
		ClassData * cl = field->getOwnerClass();\
		if(!cl->isInitialized())\
			cl->initialize();\
			\
		field->getStaticValue(word1,word2);\
		if((*p == 'J') || (*p == 'D'))\
		{\
		e_PUSH_OPERAND_STACK( (((e_j_u_long) word1)<<32)|((e_j_u_long) word2) );\
		}\
		else\
		{\
		e_PUSH_OPERAND_STACK(word1);\
		}\
	}\
	 e_CORE_getstatic_END: 

