//******************************************************************//
//*           Automatically Generated File Please Do Edit          *//
//******************************************************************//

//Description   : An Implementation for Instruction new  (0xbb) (187)        
//Generated by  : Eslam Al-Morshdy (eslam@gmx.de)                        
//for Bugs      :                                         				  
//Last Edited by:												      



//========
//CAUTIONS :
//========
//	 (1) - Nothig Goes Here or it will be Lost in later Modification !
//	 (2) - Namming Convention  for local variables of an instruction 
//	        implementation should have a prefix that refrence the instruction 



//=========
//VARIABLES :
//=========
//	 unsigned int   	  pc     ;    /* program counter   */	
//	 unsigned int*  	  op_stk ;    /* operand stack     */	
//	 unsigned int*  	  locals ;    /* local variables   */	
//	 e_byte_t*            code  ;    /*byte-code stream   */	


#define e_CORE_new 	 \
	 e_CORE_new_START:   \
 		ClassData * cl = constant_pool->getClassData(e_READ_FROM__JAVA_BYTE_STREAM_16((code_sofar+1),e_j_char));\
		Heap * heap = Heap::getInstance();\
		Object * object = heap->createObject(cl);\
		e_PUSH_OPERAND_STACK(object);\
	 e_CORE_new_END: \

