//*******************************************************************//
//*           Automatically Generated File Please Don't Edit!       *//
//*******************************************************************//


//Any required modification mail eslam@gmx.de  //


#ifndef e_const_H_
	#define e_const_H_




	#define e_VALUE_OF_nop                 0x00
	#define e_VALUE_OF_aconst_null         0x01
	#define e_VALUE_OF_iconst_m1           0x02
	#define e_VALUE_OF_iconst_0            0x03
	#define e_VALUE_OF_iconst_1            0x04
	#define e_VALUE_OF_iconst_2            0x05
	#define e_VALUE_OF_iconst_3            0x06
	#define e_VALUE_OF_iconst_4            0x07
	#define e_VALUE_OF_iconst_5            0x08
	#define e_VALUE_OF_lconst_0            0x09
	#define e_VALUE_OF_lconst_1            0x0a
	#define e_VALUE_OF_fconst_0            0x0b
	#define e_VALUE_OF_fconst_1            0x0c
	#define e_VALUE_OF_fconst_2            0x0d
	#define e_VALUE_OF_dconst_0            0x0e
	#define e_VALUE_OF_dconst_1            0x0f
	#define e_VALUE_OF_bipush              0x10
	#define e_VALUE_OF_sipush              0x11
	#define e_VALUE_OF_ldc                 0x12
	#define e_VALUE_OF_ldc_w               0x13
	#define e_VALUE_OF_ldc2_w              0x14
	#define e_VALUE_OF_iload               0x15
	#define e_VALUE_OF_lload               0x16
	#define e_VALUE_OF_fload               0x17
	#define e_VALUE_OF_dload               0x18
	#define e_VALUE_OF_aload               0x19
	#define e_VALUE_OF_iload_0             0x1a
	#define e_VALUE_OF_iload_1             0x1b
	#define e_VALUE_OF_iload_2             0x1c
	#define e_VALUE_OF_iload_3             0x1d
	#define e_VALUE_OF_lload_0             0x1e
	#define e_VALUE_OF_lload_1             0x1f
	#define e_VALUE_OF_lload_2             0x20
	#define e_VALUE_OF_lload_3             0x21
	#define e_VALUE_OF_fload_0             0x22
	#define e_VALUE_OF_fload_1             0x23
	#define e_VALUE_OF_fload_2             0x24
	#define e_VALUE_OF_fload_3             0x25
	#define e_VALUE_OF_dload_0             0x26
	#define e_VALUE_OF_dload_1             0x27
	#define e_VALUE_OF_dload_2             0x28
	#define e_VALUE_OF_dload_3             0x29
	#define e_VALUE_OF_aload_0             0x2a
	#define e_VALUE_OF_aload_1             0x2b
	#define e_VALUE_OF_aload_2             0x2c
	#define e_VALUE_OF_aload_3             0x2d
	#define e_VALUE_OF_iaload              0x2e
	#define e_VALUE_OF_laload              0x2f
	#define e_VALUE_OF_faload              0x30
	#define e_VALUE_OF_daload              0x31
	#define e_VALUE_OF_aaload              0x32
	#define e_VALUE_OF_baload              0x33
	#define e_VALUE_OF_caload              0x34
	#define e_VALUE_OF_saload              0x35
	#define e_VALUE_OF_istore              0x36
	#define e_VALUE_OF_lstore              0x37
	#define e_VALUE_OF_fstore              0x38
	#define e_VALUE_OF_dstore              0x39
	#define e_VALUE_OF_astore              0x3a
	#define e_VALUE_OF_istore_0            0x3b
	#define e_VALUE_OF_istore_1            0x3c
	#define e_VALUE_OF_istore_2            0x3d
	#define e_VALUE_OF_istore_3            0x3e
	#define e_VALUE_OF_lstore_0            0x3f
	#define e_VALUE_OF_lstore_1            0x40
	#define e_VALUE_OF_lstore_2            0x41
	#define e_VALUE_OF_lstore_3            0x42
	#define e_VALUE_OF_fstore_0            0x43
	#define e_VALUE_OF_fstore_1            0x44
	#define e_VALUE_OF_fstore_2            0x45
	#define e_VALUE_OF_fstore_3            0x46
	#define e_VALUE_OF_dstore_0            0x47
	#define e_VALUE_OF_dstore_1            0x48
	#define e_VALUE_OF_dstore_2            0x49
	#define e_VALUE_OF_dstore_3            0x4a
	#define e_VALUE_OF_astore_0            0x4b
	#define e_VALUE_OF_astore_1            0x4c
	#define e_VALUE_OF_astore_2            0x4d
	#define e_VALUE_OF_astore_3            0x4e
	#define e_VALUE_OF_iastore             0x4f
	#define e_VALUE_OF_lastore             0x50
	#define e_VALUE_OF_fastore             0x51
	#define e_VALUE_OF_dastore             0x52
	#define e_VALUE_OF_aastore             0x53
	#define e_VALUE_OF_bastore             0x54
	#define e_VALUE_OF_castore             0x55
	#define e_VALUE_OF_sastore             0x56
	#define e_VALUE_OF_pop                 0x57
	#define e_VALUE_OF_pop2                0x58
	#define e_VALUE_OF_dup                 0x59
	#define e_VALUE_OF_dup_x1              0x5a
	#define e_VALUE_OF_dup_x2              0x5b
	#define e_VALUE_OF_dup2                0x5c
	#define e_VALUE_OF_dup2_x1             0x5d
	#define e_VALUE_OF_dup2_x2             0x5e
	#define e_VALUE_OF_swap                0x5f
	#define e_VALUE_OF_iadd                0x60
	#define e_VALUE_OF_ladd                0x61
	#define e_VALUE_OF_fadd                0x62
	#define e_VALUE_OF_dadd                0x63
	#define e_VALUE_OF_isub                0x64
	#define e_VALUE_OF_lsub                0x65
	#define e_VALUE_OF_fsub                0x66
	#define e_VALUE_OF_dsub                0x67
	#define e_VALUE_OF_imul                0x68
	#define e_VALUE_OF_lmul                0x69
	#define e_VALUE_OF_fmul                0x6a
	#define e_VALUE_OF_dmul                0x6b
	#define e_VALUE_OF_idiv                0x6c
	#define e_VALUE_OF_ldiv                0x6d
	#define e_VALUE_OF_fdiv                0x6e
	#define e_VALUE_OF_ddiv                0x6f
	#define e_VALUE_OF_irem                0x70
	#define e_VALUE_OF_lrem                0x71
	#define e_VALUE_OF_frem                0x72
	#define e_VALUE_OF_drem                0x73
	#define e_VALUE_OF_ineg                0x74
	#define e_VALUE_OF_lneg                0x75
	#define e_VALUE_OF_fneg                0x76
	#define e_VALUE_OF_dneg                0x77
	#define e_VALUE_OF_ishl                0x78
	#define e_VALUE_OF_lshl                0x79
	#define e_VALUE_OF_ishr                0x7a
	#define e_VALUE_OF_lshr                0x7b
	#define e_VALUE_OF_iushr               0x7c
	#define e_VALUE_OF_lushr               0x7d
	#define e_VALUE_OF_iand                0x7e
	#define e_VALUE_OF_land                0x7f
	#define e_VALUE_OF_ior                 0x80
	#define e_VALUE_OF_lor                 0x81
	#define e_VALUE_OF_ixor                0x82
	#define e_VALUE_OF_lxor                0x83
	#define e_VALUE_OF_iinc                0x84
	#define e_VALUE_OF_i2l                 0x85
	#define e_VALUE_OF_i2f                 0x86
	#define e_VALUE_OF_i2d                 0x87
	#define e_VALUE_OF_l2i                 0x88
	#define e_VALUE_OF_l2f                 0x89
	#define e_VALUE_OF_l2d                 0x8a
	#define e_VALUE_OF_f2i                 0x8b
	#define e_VALUE_OF_f2l                 0x8c
	#define e_VALUE_OF_f2d                 0x8d
	#define e_VALUE_OF_d2i                 0x8e
	#define e_VALUE_OF_d2l                 0x8f
	#define e_VALUE_OF_d2f                 0x90
	#define e_VALUE_OF_i2b                 0x91
	#define e_VALUE_OF_i2c                 0x92
	#define e_VALUE_OF_i2s                 0x93
	#define e_VALUE_OF_lcmp                0x94
	#define e_VALUE_OF_fcmpl               0x95
	#define e_VALUE_OF_fcmpg               0x96
	#define e_VALUE_OF_dcmpl               0x97
	#define e_VALUE_OF_dcmpg               0x98
	#define e_VALUE_OF_ifeq                0x99
	#define e_VALUE_OF_ifne                0x9a
	#define e_VALUE_OF_iflt                0x9b
	#define e_VALUE_OF_ifge                0x9c
	#define e_VALUE_OF_ifgt                0x9d
	#define e_VALUE_OF_ifle                0x9e
	#define e_VALUE_OF_if_icmpeq           0x9f
	#define e_VALUE_OF_if_icmpne           0xa0
	#define e_VALUE_OF_if_icmplt           0xa1
	#define e_VALUE_OF_if_icmpge           0xa2
	#define e_VALUE_OF_if_icmpgt           0xa3
	#define e_VALUE_OF_if_icmple           0xa4
	#define e_VALUE_OF_if_acmpeq           0xa5
	#define e_VALUE_OF_if_acmpne           0xa6
	#define e_VALUE_OF_goto                0xa7
	#define e_VALUE_OF_jsr                 0xa8
	#define e_VALUE_OF_ret                 0xa9
	#define e_VALUE_OF_tableswitch         0xaa
	#define e_VALUE_OF_lookupswitch        0xab
	#define e_VALUE_OF_ireturn             0xac
	#define e_VALUE_OF_lreturn             0xad
	#define e_VALUE_OF_freturn             0xae
	#define e_VALUE_OF_dreturn             0xaf
	#define e_VALUE_OF_areturn             0xb0
	#define e_VALUE_OF_return              0xb1
	#define e_VALUE_OF_getstatic           0xb2
	#define e_VALUE_OF_putstatic           0xb3
	#define e_VALUE_OF_getfield            0xb4
	#define e_VALUE_OF_putfield            0xb5
	#define e_VALUE_OF_invokevirtual       0xb6
	#define e_VALUE_OF_invokespecial       0xb7
	#define e_VALUE_OF_invokestatic        0xb8
	#define e_VALUE_OF_invokeinterface     0xb9
	#define e_VALUE_OF_xxxunusedxxx1       0xba
	#define e_VALUE_OF_new                 0xbb
	#define e_VALUE_OF_newarray            0xbc
	#define e_VALUE_OF_anewarray           0xbd
	#define e_VALUE_OF_arraylength         0xbe
	#define e_VALUE_OF_athrow              0xbf
	#define e_VALUE_OF_checkcast           0xc0
	#define e_VALUE_OF_instanceof          0xc1
	#define e_VALUE_OF_monitorenter        0xc2
	#define e_VALUE_OF_monitorexit         0xc3
	#define e_VALUE_OF_wide                0xc4
	#define e_VALUE_OF_multianewarray      0xc5
	#define e_VALUE_OF_ifnull              0xc6
	#define e_VALUE_OF_ifnonnull           0xc7
	#define e_VALUE_OF_goto_w              0xc8
	#define e_VALUE_OF_jsr_w               0xc9
	#define e_VALUE_OF_breakpoint          0xca
	#define e_VALUE_OF_impdep1             0xfe
	#define e_VALUE_OF_impdep2             0xff
	
#endif // e_const_H_

