//******************************************************************//
//*           Automatically Generated File Please Do Edit          *//
//******************************************************************//

//Description   : An Implementation for Instruction iadd  (0x60) (096)        
//Generated by  : Eslam Al-Morshdy (eslam@gmx.de)                        
//for Bugs      :                                         				  
//Last Edited by:												      



//========
//CAUTIONS :
//========
//	 (1) - Nothig Goes Here or it will be Lost in later Modification !
//	 (2) - Namming Convention  for local variables of an instruction 
//	        implementation should have a prefix that refrence the instruction 



//=========
//VARIABLES :
//=========
//	 unsigned int   	  pc     ;    /* program counter   */	
//	 unsigned int*  	  op_stk ;    /* operand stack     */	
//	 unsigned int*  	  locals ;    /* local variables   */	
//	 e_byte_t*            code  ;     /*byte-code stream   */	


#define e_CORE_iadd 		\
e_CORE_iadd_START:  		\
	*( e_j_long* )op_stk_top = *( e_j_long * ) op_stk_top - *( op_stk_top + sizeof( e_j_long ) );\
e_CORE_iadd_END:


#define e_COMPUTE_NEXT_iadd  code_sofar++;

