//******************************************************************//
//*           Automatically Generated File Please Do Edit          *//
//******************************************************************//

//Description   : An Implementation for Instruction jsr  (0xa8) (168)        
//Generated by  : Eslam Al-Morshdy (eslam@gmx.de)                        
//for Bugs      :                                         				  
//Last Edited by:												      



//========
//CAUTIONS :
//========
//	 (1) - Nothig Goes Here or it will be Lost in later Modification !
//	 (2) - Namming Convention  for local variables of an instruction 
//	        implementation should have a prefix that refrence the instruction 



//=========
//VARIABLES :
//=========
//	 unsigned int   	  pc     ;    /* program counter   */	
//	 unsigned int*  	  op_stk ;    /* operand stack     */	
//	 unsigned int*  	  locals ;    /* local variables   */	
//	 e_byte_t*            code  ;    /*byte-code stream   */	

/*
 * push address of next on op stack
 * d goto current+ siged 16 bit
 * */
#define e_CORE_jsr 	 \
	 e_CORE_jsr_START:   \
 		e_PUSH_OPERAND_STACK((code_sofar + e_STEP_OF_jsr  ));\
 		e_PROCEDE_TO( e_READ_FROM__JAVA_BYTE_STREAM_16((code_sofar+1),e_j_short));\
  	 e_CORE_jsr_END:

