//******************************************************************//
//*           Automatically Generated File Please Do Edit          *//
//******************************************************************//

//Description   : An Implementation for Instruction return  (0xb1) (177)        
//Generated by  : Eslam Al-Morshdy (eslam@gmx.de)                        
//for Bugs      :                                         				  
//Last Edited by:												      



//========
//CAUTIONS :
//========
//	 (1) - Nothig Goes Here or it will be Lost in later Modification !
//	 (2) - Namming Convention  for local variables of an instruction 
//	        implementation should have a prefix that refrence the instruction 



//=========
//VARIABLES :
//=========
//	 unsigned int   	  pc     ;    /* program counter   */	
//	 unsigned int*  	  op_stk ;    /* operand stack     */	
//	 unsigned int*  	  locals ;    /* local variables   */	
//	 e_byte_t*            code  ;    /*byte-code stream   */	


#define e_CORE_return 	 \
//	 e_CORE_return_START:   \
	 e_frame_t* temp ;\
         pop(&java_stack , &temp);\
         if (NULL == temp){\
         	e_FREE_CURRENT_FRAME;\
         	return;\
         }else{\
         	e_SET_CURRENT_FRAME(temp)\
         	goto *e_Instruction_Label_Lookup[ *( e_j_u_byte* ) code_sofar ];\
         }\
         e_CORE_return_END: 

